services:
  grafana-tg-bot:
    env_file:
    - .env
    restart: unless-stopped
    build:
      context: .
    cap_drop:
    - ALL
    volumes:
    - ./config:/app/config:ro
    ports:
    - 8080:8080

  cache:
    env_file:
    - .env
    image: valkey/valkey:7.2.5-alpine3.19
    pull_policy: missing
    restart: unless-stopped
    cap_add:
    - ALL
    volumes:
    - cache-data:/data

volumes:
  cache-data:
